name: Bump Homebrew formula

on:
  release:
    types: [created]

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.TOKEN}}
          tap: erictsiliacos/homebrew-tap
          formula: portal
