on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: CI

jobs:
  test:
    name: Tests
    runs-on: macos-latest
    steps:
      - name: Integration Tests
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - run: go test ./...
      - run: brew uninstall bats
      - run: brew install bats-core
      - run: brew tap kaos/shell
      - run: brew install bats-assert
      - run: brew install bats-file
      - run: bats ./bats
