on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: CI

jobs:
  test:
    name: Integration Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.13
      - uses: mig4/setup-bats@v1.0.1
      - run: brew install git-duet/tap/git-duet
      - run: brew install pivotal/tap/git-together
      - run: bats ./bats
