name: Release

on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: darwin
        goarch: amd64
        
    - uses: dawidd6/action-homebrew-bump-formula@v3
      with:
        token: ${{secrets.TAP_GITHUB_TOKEN}}
        tap: erictsiliacos/homebrew-tap
        formula: portal
